import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class Report(Base):
    """Final analysis report for a completed session.

    Generated by report_node at the end of the LangGraph pipeline.
    The content field stores the full structured report as JSONB:

        {
            "synthesis": str,           # global summary of the session
            "improvement_axes": [str],  # actionable improvement recommendations
            "utterances": [             # per-utterance enriched data
                {
                    "speaker": str,
                    "start": float,
                    "end": float,
                    "text": str,
                    "intention": str,
                    "sentiment": str,
                    "issues": [str]
                },
                ...
            ]
        }
    """

    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,   # one report per session
        index=True,
    )
    content: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
